services:
  - type: web
    name: gamertavern-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://sidequest.b-jaur.com
